version: '3.8'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000" # map host port 8888 to container port 8000
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build: ./frontend/wrdu-hw-2-frontend
    ports:
      - "5173:5173" # map host port 8181 to container port 5173

  nginx:
    container_name: nginx
    image: nginx:latest
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
